# Generated by Django 5.2.15 on 2026-06-08 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('human_points', models.PositiveIntegerField(default=0)),
                ('ai_points', models.PositiveIntegerField(default=0)),
                ('human_exact_scores', models.PositiveIntegerField(default=0)),
                ('ai_exact_scores', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
