# Generated by Django 5.2.15 on 2026-06-08 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kickoff_time', models.DateTimeField()),
                ('stadium', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('group', 'Group'), ('round_of_16', 'Round of 16'), ('quarterfinal', 'Quarterfinal'), ('semifinal', 'Semifinal'), ('third_place', 'Third Place'), ('final', 'Final')], default='group', max_length=24)),
                ('actual_score_a', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_score_b', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
            ],
            options={
                'ordering': ['kickoff_time'],
            },
        ),
    ]
